environment:
  encrypt_token:
    secure: 2Tozd/hUxQZSOt/m/E5Spg==
  nodejs_version: "0.12"
  COVERALLS_GIT_BRANCH: '$(APPVEYOR_REPO_BRANCH)'
  BOWER_REPO: 'github.com/it-depends-js/it-depends-bower.git'
  BOWER_BRANCH: 'bower-publish-test'

init:
  - ps: $env:ITDEPENDS_IS_PR = (-not (-not ($env:APPVEYOR_PULL_REQUEST_NUMBER)))
  - ps: $env:ITDEPENDS_IS_MASTER = ($env:APPVEYOR_REPO_BRANCH -eq 'master')
  - ps: $env:ITDEPENDS_MASTER_NOT_PR = (($env:ITDEPENDS_IS_MASTER -eq 'True') -and (-not ($env:ITDEPENDS_IS_PR -eq 'True')))

install:
  - ps: >-
      if($env:ITDEPENDS_IS_PR -eq 'False') {
         ./build/tools/decrypt-files.ps1
      }
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g gulp

test_script:
  - gulp continous-integration

build: off

artifacts:
  - path: 'out\dist\*.js'
    name: it-depends-library
  - path: 'out\definitions\*.d.ts'
    name: typescript-definitions
  - path: 'out\reports\coverage.html'
    name: coverage-html
  - path: 'out\reports\benchmark-results.json'
    name: benchmark-results

on_success:
  - ps: >-
      if(($env:APPVEYOR_REPO_TAG_NAME) -and ($env:ITDEPENDS_MASTER_NOT_PR -eq 'True')) {
         ./build/tools/publish-npm.ps1
      }

deploy:
  tag: '$(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token:
    secure: iIQYZTIjnJwRMu4NGFO9iDWVxiULK/6RfSWY6R9Z8W7daJPdGQGMBqblEcpYa9xZ
  artifact: it-depends-library
  on:
    branch: master
    appveyor_repo_tag: true

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3e4f4d24df09d725689d
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json
