environment:matrix:
  - nodejs_version: "0.10.25"
  - nodejs_version: "0.12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g gulp

test_script:
  - gulp ci

build: off